var menu = {
    "button":[
        {
            "type":"view",
            "name":"创建",
            "url":"http://note.wenode.org/note/new"
        },
        {
            "type":"view",
            "name":"发现",
            "url":"http://note.wenode.org/note/discover"
        },
        {
            "type":"view",
            "name":"我的",
            "url":"http://note.wenode.org/note/mine"
        }
    ]
};